import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorGradient from "@/components/CursorGradient";
import MouseTrackedGrid from "@/components/MouseTrackedGrid";
import MouseTrackedContent from "@/components/MouseTrackedContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <div className="min-h-screen w-full relative">
          {/* Cursor-Following Crimson Gradient */}
          <CursorGradient />
          {/* Mouse-Tracked Grid Background */}
          <MouseTrackedGrid />
          {/* Your Content/Components */}
          <MouseTrackedContent>
            {children}
          </MouseTrackedContent>
        </div>
      </body>
    </html>
  );
}
